name: knowix_bot
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  televerse: ^2.4.4
  http: ^0.13.6
  path: ^1.9.1
  docx_to_text: ^1.0.1
  pdf: ^3.11.3
  pdfx: ^2.9.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
